infrastructure/bicep/main.bicep, infrastructure/bicep/modules/aml_computecluster.bicep, infrastructure/bicep/modules/aml_workspace.bicep, infrastructure/bicep/modules/application_insights.bicep, infrastructure/bicep/modules/container_registry.bicep, infrastructure/bicep/modules/key_vault.bicep, infrastructure/bicep/modules/storage_account.bicep, infrastructure/bicep/pipelines/bicep-ado-deploy-infra.yml, infrastructure/terraform/aml_deploy.tf, infrastructure/terraform/locals.tf, infrastructure/terraform/main.tf, infrastructure/terraform/modules/aml-workspace/main.tf, infrastructure/terraform/modules/aml-workspace/outputs.tf, infrastructure/terraform/modules/application-insights/main.tf, infrastructure/terraform/modules/application-insights/outputs.tf, infrastructure/terraform/modules/container-registry/main.tf, infrastructure/terraform/modules/container-registry/outputs.tf, infrastructure/terraform/modules/key-vault/main.tf, infrastructure/terraform/modules/key-vault/outputs.tf, infrastructure/terraform/modules/storage-account/main.tf, infrastructure/terraform/modules/storage-account/outputs.tf
Includes:
- Remove arm folder for now
- Adjust naming convention, following https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations
- Adjust modules attributes bicep vs. terraform
- Fix typos
=> Align bicep and terraform 

config-infra-dev.yml, infrastructure/bicep/main.bicep, infrastructure/bicep/modules/aml_computecluster.bicep, infrastructure/bicep/modules/aml_workspace.bicep, infrastructure/bicep/modules/application_insights.bicep, infrastructure/bicep/modules/container_registry.bicep, infrastructure/bicep/modules/key_vault.bicep, infrastructure/bicep/modules/storage_account.bicep, infrastructure/bicep/pipelines/bicep-ado-deploy-infra.yml, infrastructure/terraform/aml_deploy.tf, infrastructure/terraform/main.tf, infrastructure/terraform/modules/aml-workspace/main.tf, infrastructure/terraform/modules/aml-workspace/variables.tf, infrastructure/terraform/modules/application-insights/main.tf, infrastructure/terraform/modules/application-insights/variables.tf, infrastructure/terraform/modules/container-registry/main.tf, infrastructure/terraform/modules/container-registry/variables.tf, infrastructure/terraform/modules/key-vault/main.tf, infrastructure/terraform/modules/key-vault/variables.tf, infrastructure/terraform/modules/resource-group/main.tf, infrastructure/terraform/modules/resource-group/variables.tf, infrastructure/terraform/modules/storage-account/main.tf, infrastructure/terraform/modules/storage-account/variables.tf, infrastructure/terraform/pipelines/tf-ado-deploy-infra.yml
Include -
- Added env var to the naming convention CH
- Test ado pipelines
=> Test ado pipelines

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/repository-issue.md, .github/ISSUE_TEMPLATE/solution-accelerator-request.md, .github/PULL_REQUEST_TEMPLATE.md
* Adding Issue, Pull Request, and accelerator request template
=> Adding the github templates

infrastructure/bicep/pipelines/bicep-ado-deploy-infra.yml
I have:
in bicep infra azure pipeline I changed the environment to be driven by yaml files
fixes #
=> made env driven by yaml file

cv/aml-cli-v2/data-science/src/image_io.py, cv/aml-cli-v2/data-science/src/model/model_loader.py, cv/aml-cli-v2/data-science/src/model/swin_models.py, cv/aml-cli-v2/data-science/src/model/test_model.py, cv/aml-cli-v2/data-science/src/model/torchvision_models.py, cv/aml-cli-v2/data-science/src/profiling.py, cv/aml-cli-v2/data-science/src/train.py
I have:
Added Jeff as the original author of the CV code. 
-
fixes #
None
=> CV Author patch

classical/aml-cli-v2/mlops/devops-pipelines/deploy-online-endpoint-pipeline.yml
=> fixed unique endpoint name req

classical/aml-cli-v2/mlops/devops-pipelines/deploy-batch-endpoint-pipeline.yml, classical/aml-cli-v2/mlops/devops-pipelines/deploy-model-training-pipeline.yml, classical/aml-cli-v2/mlops/devops-pipelines/deploy-online-endpoint-pipeline.yml, config-infra-prod.yml, cv/aml-cli-v2/mlops/devops-pipelines/deploy-model-training-pipeline.yml
I have:
- [ x] read and followed the contributing guidelines
- I would like to introduce experiment name and display (run) names as two additional parameters. It helps me to locate my experiments that I am running on my own branch.
fixes #
=> exp and display parameters

classical/aml-cli-v2/mlops/devops-pipelines/deploy-batch-endpoint-pipeline.yml, classical/aml-cli-v2/mlops/devops-pipelines/deploy-online-endpoint-pipeline.yml, classical/python-sdk/data-science/src/evaluate.py, classical/python-sdk/data-science/src/prep.py, classical/python-sdk/data-science/src/train.py, config-infra-prod.yml
I have:
- Remove run-id from path in custom data science scripts (included at the pipeline creation level by this PR: https://github.com/Azure/mlops-templates/pull/14)
=> SDK - Run ID included in the data paths in pipeline definition

config-infra-dev.yml, config-infra-prod.yml, infrastructure/terraform/aml_deploy.tf, infrastructure/terraform/modules/data-explorer/main.tf, infrastructure/terraform/modules/data-explorer/outputs.tf, infrastructure/terraform/modules/data-explorer/variables.tf, infrastructure/terraform/modules/key-vault/main.tf, infrastructure/terraform/pipelines/tf-ado-deploy-infra.yml, infrastructure/terraform/variables.tf
I have:
- Adding monitoring option for infrastructure deployment by setting enable_monitoring option in config files
- Adding step in tf-ado-deploy-infra pipeline to create service principal secret variable that can be registered in key vault for future use
- Adding terraform module for ADX deployment and key vault secret creation if enable_monitoring is set
=> monitoring infrastructure deployment

classical/python-sdk/config-aml.yml, classical/python-sdk/data-science/environment/train.yml, classical/python-sdk/data-science/src/evaluate.py, classical/python-sdk/data-science/src/prep.py, classical/python-sdk/data-science/src/score.py, classical/python-sdk/data-science/src/train.py, classical/python-sdk/mlops/devops-pipelines/deploy-model-training-pipeline.yml
I have:
Adapt project code to template changes from PR https://github.com/Azure/mlops-templates/pull/19
- Specify `build_type` in env creation
- New `training_arguments` param in AML config
- Dataset path changes since multiple are supported now
(+ missing copyright lines)
=> SDK classical - adapt project to template changes

.gitignore
=> remove lib/ from gitignore because it's needed for nodejs

classical/python-sdk/mlops/devops-pipelines/deploy-model-batch-scoring.yml
I have:
- Adapt scoring pipeline to changes from https://github.com/Azure/mlops-templates/pull/19 (added build type when creating environment)
=> SDK classical - adapt scoring pipeline to template changes

classical/aml-cli-v2/mlops/azureml/deploy/online/online-deployment.yml
=> increased instance node size to fix out of memory error

nlp/aml-cli-v2/mlops/devops-pipelines/deploy-model-training-pipeline.yml
=> Fix NLP builds post testing

nlp/aml-cli-v2/mlops/devops-pipelines/deploy-online-endpoint-pipeline.yml
=> fix endpoint name being too long

.gitignore
=> remove lib needed for node.js

config-infra-dev.yml, config-infra-prod.yml
I have:
- [x ] read and followed the contributing guidelines
- change enable_monitoring to false
fixes #
=> disable monitoring

nlp/aml-cli-v2/mlops/azureml/train/pipeline.yml
=> Fix force comparison argument value

config-infra-dev.yml, config-infra-prod.yml
=> Tf name fix

classical/aml-cli-v2/mlops/github-actions/deploy-batch-endpoint-pipeline-classical.yml, classical/aml-cli-v2/mlops/github-actions/deploy-online-endpoint-pipeline-classical.yml
I have:
Updated endpoint names with prefix
-
fixes #
=> Gha endpoint update

classical/python-sdk/data-science/src/prep.py, infrastructure/terraform/modules/data-explorer/outputs.tf
Reverts Azure/mlops-project-template#69
=> Revert "remove data-explorer tf outputs & typo"

config-infra-dev.yml, config-infra-prod.yml
Reverts Azure/mlops-project-template#68
=> Revert "disable monitoring"

classical/aml-cli-v2/data-science/environment/train-requirements.txt
I have:
-
fixes #
re add train-requirements.txt file
=> re add train-requirements.txt to environments directory

classical/aml-cli-v2/mlops/devops-pipelines/deploy-online-endpoint-pipeline.yml, nlp/aml-cli-v2/mlops/devops-pipelines/deploy-online-endpoint-pipeline.yml
Updated template path for dev infra so template would run successfully
I have:
- 
- [✅ ]  read and followed the contributing guidelines
-
fixes #
Updated endpoint deployment template for AML-CLI. Path navigation was incorrect
=> Updating template path for dev infra config

config-infra-dev.yml, config-infra-prod.yml
=> Tfsec rollback

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, environment.yml
I have:
- [x ] read and followed the contributing guidelines
- added Devcontainer to support GitHub Codespaces
fixes #
=> GitHub Codespaces support - added Devcontainer

classical/aml-cli-v2/mlops/devops-pipelines/deploy-batch-endpoint-pipeline.yml, classical/aml-cli-v2/mlops/devops-pipelines/deploy-model-training-pipeline.yml, classical/aml-cli-v2/mlops/devops-pipelines/deploy-online-endpoint-pipeline.yml, classical/python-sdk-v1/mlops/devops-pipelines/deploy-model-batch-scoring.yml, classical/python-sdk-v1/mlops/devops-pipelines/deploy-model-training-pipeline.yml, classical/python-sdk-v2/mlops/devops-pipelines/deploy-batch-endpoint-pipeline.yml, classical/python-sdk-v2/mlops/devops-pipelines/deploy-model-training-pipeline.yml, classical/python-sdk-v2/mlops/devops-pipelines/deploy-online-endpoint-pipeline.yml, classical/rai-aml-cli-v2/mlops/devops-pipelines/deploy-batch-endpoint-pipeline.yml, classical/rai-aml-cli-v2/mlops/devops-pipelines/deploy-model-training-pipeline.yml, classical/rai-aml-cli-v2/mlops/devops-pipelines/deploy-online-endpoint-pipeline.yml, classical/rai-aml-cli-v2/mlops/devops-pipelines/trigger_.code-search, cv/aml-cli-v2/mlops/devops-pipelines/deploy-model-training-pipeline.yml, cv/aml-cli-v2/mlops/devops-pipelines/deploy-online-endpoint-pipeline.yml, cv/python-sdk-v1/mlops/devops-pipelines/deploy-model-training-pipeline.yml, infrastructure/bicep/pipelines/bicep-ado-deploy-infra.yml, infrastructure/terraform/devops-pipelines/tf-ado-deploy-infra.yml, nlp/aml-cli-v2/mlops/devops-pipelines/deploy-model-training-pipeline.yml, nlp/aml-cli-v2/mlops/devops-pipelines/deploy-online-endpoint-pipeline.yml, nlp/python-sdk-v2/mlops/devops-pipelines/deploy-model-training-pipeline.yml
I have:
- [* ] read and followed the contributing guidelines
-
fixes #
All fixes related to Azure DevOps deployment:
* Modified all pipelines to checkout from local Azure DevOps project clone of MLOps V2 repos. No github service connections are necessary and no editing at pipeline run time.
* Fix typo in none trigger in all pipelines so failing automatic executions of pipelines do not occur after initialize-repo.
* Remove unnecessary '2' from endpoint name for taxi-fare-regression batch endpoint
* Pre-create mlops-templates checkout directory in all pipelines to clear "##[warning]Unable move and reuse existing repository to required location." messages during pipeline runs.
* Add descriptive text to pipeline runs as pipeline executions are all named for the repository.
Matching …
=> Azure DevOps deployment updates
